Update to Fedora 42

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -14,7 +14,7 @@ jobs:
       uses: actions/checkout@v4
 
     - name: Install Dependencies
-      run: dnf install -y dnf-plugins-core patch rpm-build copr-cli
+      run: dnf install -y dnf5-plugins patch rpm-build copr-cli
 
     - name: Rebuild SRPM
       run: |
@@ -22,7 +22,7 @@ jobs:
         rpm -ivh --define "_topdir ${GITHUB_WORKSPACE}" *.src.rpm &&
         for patch in SPECS-PATCHES/*.patch; do
           pushd SPECS > /dev/null;
-          patch -p0 < "../$patch" || { echo "Patch $patch Failed!"; exit 1; }
+          patch -p1 < "../$patch" || { echo "Patch $patch Failed!"; exit 1; }
           popd  > /dev/null;
         done &&
         rpmbuild --define "_topdir ${GITHUB_WORKSPACE}" -bs SPECS/*.spec
